title: SAMple Blog
author: Sam
email: hicksey14@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog built as a sample to learn github pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
